// webpage.h - interfata web (dashboard) servita din flash
// Generat automat. NU contine date demo.
#pragma once

static const char INDEX_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"ro\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "<title>Asistent Vocal ESP32-S3</title>\n"
    "<style>\n"
    "  * { margin:0; padding:0; box-sizing:border-box; }\n"
    "  :root{\n"
    "    --bg:#eef2f7; --card:#ffffff; --ink:#1e293b; --muted:#64748b;\n"
    "    --line:#e2e8f0; --accent:#2563eb; --accent2:#7c3aed;\n"
    "    --green:#10b981; --amber:#f59e0b; --red:#ef4444; --shadow:0 1px 3px rgba(15,23,42,.08),0 8px 24px rgba(15,23,42,.06);\n"
    "  }\n"
    "  body{ font-family:system-ui,-apple-system,\"Segoe UI\",Roboto,sans-serif;\n"
    "        background:var(--bg); color:var(--ink); line-height:1.5; padding:20px; }\n"
    "  .wrap{ max-width:1100px; margin:0 auto; }\n"
    "\n"
    "  header{ display:flex; align-items:center; justify-content:space-between;\n"
    "          margin-bottom:22px; flex-wrap:wrap; gap:12px; }\n"
    "  .brand{ display:flex; align-items:center; gap:12px; }\n"
    "  .logo{ width:42px; height:42px; border-radius:12px;\n"
    "         background:linear-gradient(135deg,var(--accent),var(--accent2));\n"
    "         display:grid; place-items:center; color:#fff; font-weight:800; font-size:18px;\n"
    "         box-shadow:var(--shadow); }\n"
    "  .brand h1{ font-size:20px; font-weight:700; letter-spacing:-.2px; }\n"
    "  .brand p{ font-size:12.5px; color:var(--muted); }\n"
    "  .conn{ display:flex; align-items:center; gap:8px; background:var(--card);\n"
    "         padding:8px 14px; border-radius:999px; box-shadow:var(--shadow); font-size:13px; font-weight:600; }\n"
    "  .dot{ width:9px; height:9px; border-radius:50%; background:var(--red); transition:.3s; }\n"
    "  .dot.on{ background:var(--green); box-shadow:0 0 0 4px rgba(16,185,129,.15); }\n"
    "\n"
    "  .grid{ display:grid; grid-template-columns:repeat(12,1fr); gap:16px; }\n"
    "  .card{ background:var(--card); border-radius:16px; padding:18px 20px;\n"
    "         box-shadow:var(--shadow); border:1px solid var(--line); }\n"
    "  .card h2{ font-size:13px; text-transform:uppercase; letter-spacing:.6px;\n"
    "            color:var(--muted); margin-bottom:14px; font-weight:700; display:flex; align-items:center; gap:8px;}\n"
    "  .col4{ grid-column:span 4; } .col6{ grid-column:span 6; }\n"
    "  .col8{ grid-column:span 8; } .col12{ grid-column:span 12; }\n"
    "  @media(max-width:820px){ .col4,.col6,.col8{ grid-column:span 12; } }\n"
    "\n"
    "  /* mod */\n"
    "  .mode-row{ display:flex; align-items:center; justify-content:space-between; }\n"
    "  .mode-name{ font-size:26px; font-weight:800; letter-spacing:-.5px; }\n"
    "  .mode-name.online{ color:var(--accent); } .mode-name.offline{ color:var(--green); }\n"
    "  .sub{ font-size:12.5px; color:var(--muted); margin-top:2px; }\n"
    "  .toggle{ display:inline-flex; background:var(--bg); border-radius:10px; padding:4px; gap:4px; }\n"
    "  .toggle button{ border:0; background:transparent; padding:8px 14px; border-radius:8px;\n"
    "                  font-weight:600; font-size:13px; color:var(--muted); cursor:pointer; transition:.2s; }\n"
    "  .toggle button.active{ background:var(--card); color:var(--ink); box-shadow:var(--shadow); }\n"
    "\n"
    "  /* statistici */\n"
    "  .stat{ display:flex; flex-direction:column; gap:2px; }\n"
    "  .stat .v{ font-size:30px; font-weight:800; letter-spacing:-1px; }\n"
    "  .stat .k{ font-size:12px; color:var(--muted); }\n"
    "  .stats{ display:flex; gap:26px; }\n"
    "\n"
    "  /* metrice senzor */\n"
    "  .metrics{ display:flex; gap:16px; margin-bottom:6px; }\n"
    "  .metric{ flex:1; text-align:center; padding:10px; border-radius:12px; background:var(--bg); }\n"
    "  .metric .mv{ font-size:24px; font-weight:800; }\n"
    "  .metric .ml{ font-size:11.5px; color:var(--muted); text-transform:uppercase; letter-spacing:.5px; }\n"
    "  .metric.temp .mv{ color:var(--amber); } .metric.hum .mv{ color:var(--accent); }\n"
    "  canvas{ width:100%; height:150px; display:block; }\n"
    "\n"
    "  /* control */\n"
    "  .btns{ display:flex; gap:10px; flex-wrap:wrap; }\n"
    "  .btn{ flex:1; min-width:90px; border:0; padding:13px 10px; border-radius:12px; cursor:pointer;\n"
    "        font-weight:700; font-size:13.5px; transition:.15s; display:flex; flex-direction:column; align-items:center; gap:5px; }\n"
    "  .btn:active{ transform:scale(.97); }\n"
    "  .btn .ic{ font-size:18px; }\n"
    "  .btn.on{ background:rgba(16,185,129,.12); color:var(--green); }\n"
    "  .btn.off{ background:rgba(239,68,68,.10); color:var(--red); }\n"
    "  .btn.blink{ background:rgba(245,158,11,.12); color:var(--amber); }\n"
    "\n"
    "  /* istoric conversatii */\n"
    "  .chat{ display:flex; flex-direction:column; gap:10px; max-height:300px; overflow-y:auto; padding-right:4px; }\n"
    "  .msg{ max-width:78%; padding:10px 13px; border-radius:14px; font-size:13.5px; line-height:1.45; }\n"
    "  .msg.q{ align-self:flex-end; background:var(--accent); color:#fff; border-bottom-right-radius:4px; }\n"
    "  .msg.a{ align-self:flex-start; background:var(--bg); color:var(--ink); border-bottom-left-radius:4px; }\n"
    "  .empty{ color:var(--muted); font-size:13px; text-align:center; padding:30px 0; }\n"
    "  .ask{ display:flex; gap:8px; margin-top:12px; }\n"
    "  .ask input{ flex:1; border:1px solid var(--line); background:var(--bg); border-radius:10px;\n"
    "              padding:11px 14px; font-size:14px; color:var(--ink); outline:none; }\n"
    "  .ask input:focus{ border-color:var(--accent); }\n"
    "  .ask button{ border:0; background:var(--accent); color:#fff; border-radius:10px;\n"
    "               padding:0 18px; font-weight:700; cursor:pointer; font-size:14px; }\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"wrap\">\n"
    "  <header>\n"
    "    <div class=\"brand\">\n"
    "      <div class=\"logo\">VA</div>\n"
    "      <div>\n"
    "        <h1>Asistent Vocal ESP32-S3</h1>\n"
    "        <p>Panou de control și monitorizare</p>\n"
    "      </div>\n"
    "    </div>\n"
    "    <div class=\"conn\"><span class=\"dot\" id=\"dot\"></span><span id=\"connTxt\">conectare…</span></div>\n"
    "  </header>\n"
    "\n"
    "  <div class=\"grid\">\n"
    "    <!-- MOD -->\n"
    "    <div class=\"card col6\">\n"
    "      <h2>Mod de funcționare</h2>\n"
    "      <div class=\"mode-row\">\n"
    "        <div>\n"
    "          <div class=\"mode-name online\" id=\"modeName\">ONLINE</div>\n"
    "          <div class=\"sub\" id=\"modeSub\">dialog conversațional prin server</div>\n"
    "        </div>\n"
    "        <div class=\"toggle\">\n"
    "          <button id=\"mOnline\" class=\"active\" onclick=\"setMode('online')\">Online</button>\n"
    "          <button id=\"mOffline\" onclick=\"setMode('offline')\">Offline</button>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- STATISTICI -->\n"
    "    <div class=\"card col6\">\n"
    "      <h2>Activitate</h2>\n"
    "      <div class=\"stats\">\n"
    "        <div class=\"stat\"><span class=\"v\" id=\"wakes\">0</span><span class=\"k\">activări</span></div>\n"
    "        <div class=\"stat\"><span class=\"v\" id=\"lastCmd\" style=\"font-size:16px;line-height:1.9\">—</span><span class=\"k\">ultima comandă</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- CONTROL -->\n"
    "    <div class=\"card col4\">\n"
    "      <h2>Control lampă</h2>\n"
    "      <div class=\"btns\">\n"
    "        <button class=\"btn on\" onclick=\"cmd('light','on')\"><span class=\"ic\">●</span>Aprinde</button>\n"
    "        <button class=\"btn off\" onclick=\"cmd('light','off')\"><span class=\"ic\">○</span>Stinge</button>\n"
    "        <button class=\"btn blink\" onclick=\"cmd('light','blink')\"><span class=\"ic\">◐</span>Clipește</button>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- SENZOR + GRAFIC -->\n"
    "    <div class=\"card col8\">\n"
    "      <h2>Mediu — temperatură &amp; umiditate</h2>\n"
    "      <div class=\"metrics\">\n"
    "        <div class=\"metric temp\"><div class=\"mv\"><span id=\"tVal\">—</span>°C</div><div class=\"ml\">Temperatură</div></div>\n"
    "        <div class=\"metric hum\"><div class=\"mv\"><span id=\"hVal\">—</span>%</div><div class=\"ml\">Umiditate</div></div>\n"
    "      </div>\n"
    "      <canvas id=\"chart\"></canvas>\n"
    "    </div>\n"
    "\n"
    "    <!-- ISTORIC -->\n"
    "    <div class=\"card col12\">\n"
    "      <h2>Istoric conversații (mod online)</h2>\n"
    "      <div class=\"chat\" id=\"chat\">\n"
    "        <div class=\"empty\" id=\"chatEmpty\">Nicio conversație încă. Rostește „Hi, ESP\" și pune o întrebare.</div>\n"
    "      </div>\n"
    "      <div class=\"ask\">\n"
    "        <input id=\"askIn\" placeholder=\"Scrie o întrebare pentru asistent…\" onkeydown=\"if(event.key==='Enter')sendAsk()\">\n"
    "        <button onclick=\"sendAsk()\">Trimite</button>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "// ---------- WebSocket ----------\n"
    "let ws, tHist=[], hHist=[];\n"
    "function connect(){\n"
    "  ws = new WebSocket('ws://'+location.host+'/ws');\n"
    "  ws.onopen   = ()=>{ setConn(true); };\n"
    "  ws.onclose  = ()=>{ setConn(false); setTimeout(connect,2000); };\n"
    "  ws.onmessage= e=>{ try{ handle(JSON.parse(e.data)); }catch(_){} };\n"
    "}\n"
    "function setConn(ok){\n"
    "  document.getElementById('dot').classList.toggle('on',ok);\n"
    "  document.getElementById('connTxt').textContent = ok?'conectat':'deconectat';\n"
    "}\n"
    "function send(obj){ if(ws&&ws.readyState===1) ws.send(JSON.stringify(obj)); }\n"
    "function dec(s){ try{ return decodeURIComponent(s); }catch(_){ return s; } }\n"
    "\n"
    "// ---------- comenzi ----------\n"
    "function cmd(c,v){ send({cmd:c,val:v}); }\n"
    "function setMode(m){ send({cmd:'mode',val:m}); applyMode(m); }\n"
    "function sendAsk(){\n"
    "  const i=document.getElementById('askIn'); const t=i.value.trim();\n"
    "  if(!t) return; send({cmd:'ask',text:t}); addMsg(t,'q'); i.value='';\n"
    "}\n"
    "\n"
    "// ---------- aplicare stare ----------\n"
    "function applyMode(m){\n"
    "  const n=document.getElementById('modeName');\n"
    "  n.textContent=m.toUpperCase(); n.className='mode-name '+m;\n"
    "  document.getElementById('modeSub').textContent =\n"
    "     m==='online'?'dialog conversațional prin server':'comenzi locale, fără internet';\n"
    "  document.getElementById('mOnline').classList.toggle('active',m==='online');\n"
    "  document.getElementById('mOffline').classList.toggle('active',m==='offline');\n"
    "}\n"
    "function handle(d){\n"
    "  if(d.type==='state'){\n"
    "    if(d.mode) applyMode(d.mode);\n"
    "    if(d.wakes!=null) document.getElementById('wakes').textContent=d.wakes;\n"
    "    if(d.last) document.getElementById('lastCmd').textContent=d.last;\n"
    "    if(d.temp!=null){ document.getElementById('tVal').textContent=d.temp.toFixed(1); pushData(d.temp,d.hum); }\n"
    "    if(d.hum!=null)  document.getElementById('hVal').textContent=Math.round(d.hum);\n"
    "  } else if(d.type==='conv'){\n"
    "    if(d.q) addMsg(dec(d.q),'q'); if(d.a) addMsg(dec(d.a),'a');\n"
    "  }\n"
    "}\n"
    "\n"
    "// ---------- istoric chat ----------\n"
    "function addMsg(txt,cls){\n"
    "  const c=document.getElementById('chat'); const e=document.getElementById('chatEmpty');\n"
    "  if(e) e.remove();\n"
    "  const m=document.createElement('div'); m.className='msg '+cls; m.textContent=txt;\n"
    "  c.appendChild(m); c.scrollTop=c.scrollHeight;\n"
    "}\n"
    "\n"
    "// ---------- grafic canvas ----------\n"
    "const cv=document.getElementById('chart'), ctx=cv.getContext('2d');\n"
    "function pushData(t,h){\n"
    "  tHist.push(t); hHist.push(h==null?hHist[hHist.length-1]||0:h);\n"
    "  if(tHist.length>40){ tHist.shift(); hHist.shift(); }\n"
    "  draw();\n"
    "}\n"
    "function draw(){\n"
    "  const dpr=window.devicePixelRatio||1, W=cv.clientWidth, H=cv.clientHeight;\n"
    "  cv.width=W*dpr; cv.height=H*dpr; ctx.setTransform(dpr,0,0,dpr,0,0);\n"
    "  ctx.clearRect(0,0,W,H);\n"
    "  const pad=24;\n"
    "  // grid\n"
    "  ctx.strokeStyle='#eef2f7'; ctx.lineWidth=1;\n"
    "  for(let i=0;i<=4;i++){ const y=pad+(H-2*pad)*i/4; ctx.beginPath(); ctx.moveTo(pad,y); ctx.lineTo(W-pad,y); ctx.stroke(); }\n"
    "  const series=(arr,color,min,max)=>{\n"
    "    if(arr.length<2) return;\n"
    "    ctx.strokeStyle=color; ctx.lineWidth=2.5; ctx.beginPath();\n"
    "    arr.forEach((v,i)=>{\n"
    "      const x=pad+(W-2*pad)*i/(arr.length-1);\n"
    "      const y=H-pad-(H-2*pad)*((v-min)/(max-min||1));\n"
    "      i?ctx.lineTo(x,y):ctx.moveTo(x,y);\n"
    "    });\n"
    "    ctx.stroke();\n"
    "    // ultimul punct\n"
    "    const i=arr.length-1, x=W-pad, y=H-pad-(H-2*pad)*((arr[i]-min)/(max-min||1));\n"
    "    ctx.fillStyle=color; ctx.beginPath(); ctx.arc(x,y,3.5,0,7); ctx.fill();\n"
    "  };\n"
    "  series(tHist,'#f59e0b',0,40);\n"
    "  series(hHist,'#2563eb',0,100);\n"
    "}\n"
    "window.addEventListener('resize',draw);\n"
    "\n"
    "// demo local data dacă nu vine nimic (se elimină în firmware real)\n"
    "connect();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    "\n";